# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('days', models.IntegerField(default=0)),
                ('charges', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('interest', models.DecimalField(decimal_places=5, max_digits=6)),
                ('fund', models.IntegerField(default=0)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reverse_repo.categories')),
            ],
        ),
    ]
